export type Alcada = {
    NUCHAVE: string,
    EVENTO: string,
    'ViewEventoLiberacao.DESCRICAO': string,
    CODUSUSOLICIT: string,
    'Solicitante.NOMEUSU': string,
    CODUSULIB: string,
    'Usuario.NOMEUSU': string,
    'Usuario.AD_WPPLIB': string,
    VLRATUAL: string,
    DHSOLICIT: string,
    OBSERVACAO: string,
    OBSLIB: string,
    CODPARC: string,
    'Parceiro.NOMEPARC': string,
    CODEMP: '1',
    'Empresa.NOMEFANTASIA': string,
    CODVEND: string,
    'Vendedor.APELIDO': string,
    DTNEG: string,
    CODTIPOPER: string,
    'TipoOperacao.DESCROPER': string,
    VLRNOTA: string,
    TOTALDESCONTONOTA: string,
}